const seatSwapContract = {
  address: "0xB230D9b94e4adee2Fe9b11d47D0d3EDba440DEF4" as `0x${string}`,
  ABI: [
    {
      type: "constructor",
      inputs: [
        { name: "initialOwner", type: "address", internalType: "address" },
        { name: "usdcAddress", type: "address", internalType: "address" },
      ],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "Posts",
      inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      outputs: [
        { name: "transactionId", type: "uint256", internalType: "uint256" },
        { name: "costAmount", type: "uint256", internalType: "uint256" },
        { name: "quantity", type: "uint256", internalType: "uint256" },
        { name: "seller", type: "address", internalType: "address" },
        { name: "buyer", type: "address", internalType: "address" },
        { name: "sellerConfirmed", type: "bool", internalType: "bool" },
        { name: "buyerConfirmed", type: "bool", internalType: "bool" },
        { name: "disputed", type: "bool", internalType: "bool" },
        { name: "description", type: "string", internalType: "string" },
        { name: "closed", type: "bool", internalType: "bool" },
        { name: "escrowAddress", type: "address", internalType: "address" },
      ],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "USDC",
      inputs: [],
      outputs: [{ name: "", type: "address", internalType: "contract IERC20" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "addResolver",
      inputs: [{ name: "resolver", type: "address", internalType: "address" }],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "buyerConfirm",
      inputs: [
        { name: "transactionId", type: "uint256", internalType: "uint256" },
      ],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "checkIsResolver",
      inputs: [{ name: "account", type: "address", internalType: "address" }],
      outputs: [{ name: "", type: "bool", internalType: "bool" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "closeFactory",
      inputs: [],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "closeListing",
      inputs: [
        { name: "transactionId", type: "uint256", internalType: "uint256" },
      ],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "createDispute",
      inputs: [
        { name: "transactionId", type: "uint256", internalType: "uint256" },
      ],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "displayOpenTickets",
      inputs: [],
      outputs: [
        {
          name: "",
          type: "tuple[]",
          internalType: "struct TicketFactory.TicketPost[]",
          components: [
            { name: "transactionId", type: "uint256", internalType: "uint256" },
            { name: "costAmount", type: "uint256", internalType: "uint256" },
            { name: "quantity", type: "uint256", internalType: "uint256" },
            { name: "seller", type: "address", internalType: "address" },
            { name: "buyer", type: "address", internalType: "address" },
            { name: "sellerConfirmed", type: "bool", internalType: "bool" },
            { name: "buyerConfirmed", type: "bool", internalType: "bool" },
            { name: "disputed", type: "bool", internalType: "bool" },
            { name: "description", type: "string", internalType: "string" },
            { name: "closed", type: "bool", internalType: "bool" },
            { name: "escrowAddress", type: "address", internalType: "address" },
          ],
        },
      ],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "getResolvers",
      inputs: [],
      outputs: [{ name: "", type: "address[]", internalType: "address[]" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "isResolver",
      inputs: [{ name: "", type: "address", internalType: "address" }],
      outputs: [{ name: "", type: "bool", internalType: "bool" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "listTicket",
      inputs: [
        { name: "costAmount", type: "uint256", internalType: "uint256" },
        { name: "quantity", type: "uint256", internalType: "uint256" },
        { name: "description", type: "string", internalType: "string" },
      ],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "opened",
      inputs: [],
      outputs: [{ name: "", type: "bool", internalType: "bool" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "owner",
      inputs: [],
      outputs: [{ name: "", type: "address", internalType: "address" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "purchaseTicket",
      inputs: [
        { name: "transactionId", type: "uint256", internalType: "uint256" },
      ],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "removeResolver",
      inputs: [{ name: "resolver", type: "address", internalType: "address" }],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "renounceOwnership",
      inputs: [],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "resolveDispute",
      inputs: [
        { name: "transactionId", type: "uint256", internalType: "uint256" },
        { name: "winner", type: "address", internalType: "address" },
      ],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "resolvers",
      inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      outputs: [{ name: "", type: "address", internalType: "address" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "sellerConfirm",
      inputs: [
        { name: "transactionId", type: "uint256", internalType: "uint256" },
      ],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "transactionCounter",
      inputs: [],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "transferOwnership",
      inputs: [{ name: "newOwner", type: "address", internalType: "address" }],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "event",
      name: "OwnershipTransferred",
      inputs: [
        {
          name: "previousOwner",
          type: "address",
          indexed: true,
          internalType: "address",
        },
        {
          name: "newOwner",
          type: "address",
          indexed: true,
          internalType: "address",
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "ResolverAdded",
      inputs: [
        {
          name: "resolver",
          type: "address",
          indexed: true,
          internalType: "address",
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "ResolverRemoved",
      inputs: [
        {
          name: "resolver",
          type: "address",
          indexed: true,
          internalType: "address",
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "TicketBid",
      inputs: [
        {
          name: "transactionId",
          type: "uint256",
          indexed: true,
          internalType: "uint256",
        },
        {
          name: "EscowAddress",
          type: "address",
          indexed: false,
          internalType: "address",
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "TicketListed",
      inputs: [
        {
          name: "transactionId",
          type: "uint256",
          indexed: true,
          internalType: "uint256",
        },
        {
          name: "post",
          type: "tuple",
          indexed: false,
          internalType: "struct TicketFactory.TicketPost",
          components: [
            { name: "transactionId", type: "uint256", internalType: "uint256" },
            { name: "costAmount", type: "uint256", internalType: "uint256" },
            { name: "quantity", type: "uint256", internalType: "uint256" },
            { name: "seller", type: "address", internalType: "address" },
            { name: "buyer", type: "address", internalType: "address" },
            { name: "sellerConfirmed", type: "bool", internalType: "bool" },
            { name: "buyerConfirmed", type: "bool", internalType: "bool" },
            { name: "disputed", type: "bool", internalType: "bool" },
            { name: "description", type: "string", internalType: "string" },
            { name: "closed", type: "bool", internalType: "bool" },
            { name: "escrowAddress", type: "address", internalType: "address" },
          ],
        },
      ],
      anonymous: false,
    },
    {
      type: "error",
      name: "OwnableInvalidOwner",
      inputs: [{ name: "owner", type: "address", internalType: "address" }],
    },
    {
      type: "error",
      name: "OwnableUnauthorizedAccount",
      inputs: [{ name: "account", type: "address", internalType: "address" }],
    },
  ] as const,
};

export default seatSwapContract;
